name: CI

on:
  push:
  
jobs:

  build:
  
    runs-on: ubuntu-latest
  
    steps:
    
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '8'
          distribution: 'temurin'
          
      - name: Compilacion
        run: |
          mvn package
          
      #- name: Test Unitarios
        #run: |
          #mvn package test
          
      #- name: ejecución de pruebas
        #run: |
          #mvn pdf:pdf
          
      - name: Unit Test 
        run: |
          mvn clean verify

      - name: Generate report jacoco
        run: mvn jacoco:report

      - name: JaCoCo Code Coverage Report
        id: jacoco_reporter
        uses: PavanMudigonda/jacoco-reporter@v5.0
        with:
          coverage_results_path: target/site/jacoco/jacoco.xml
          coverage_report_name: Coverage
          coverage_report_title: JaCoCo
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_check_run: false
          minimum_coverage: 70
          fail_below_threshold: true
          publish_only_summary: false
          
      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco



          
  deploy:
  
    needs: build
    
    runs-on: self-hosted
    
    steps:
    
      - name: Clonacion de repositorio para deploy
        uses: actions/checkout@v4
        
      - name: Despliegue local
        run: |
          kubectl apply -f deploy.yaml


  testjmeter:
  
      needs: deploy
      
      runs-on: self-hosted
      
      steps:
        - name: Run JMeter Action on a test
          uses: rbhadti94/apache-jmeter-action@v0.5.0
          with:
            testFilePath: test_plan.jmx
            outputReportsFolder: reports/
            args: "--loglevel INFO"
            
        - name: Upload JMeter Report
          uses: actions/upload-artifact@v4
          with:
            name: jmeter-test-results
            path: reports/
